// Public routes mapped to dedicated Prisma tables. No content is stored here.
const landingTables = [
  {
    slug: 'wellness-lounge',
    model: 'landingWellnessLounge',
    sectionFields: ['id', 'title', 'subtitle', 'actionLabel'],
    itemModel: 'landingWellnessLoungeItem',
    itemFields: [
      'id',
      'name',
      'description',
      'image',
      'color',
      'imageUrl',
      'videoUrl',
    ],
  },
  {
    slug: 'holistic-solutions',
    model: 'landingHolisticSolutions',
    sectionFields: ['id', 'title', 'subtitle', 'actionLabel'],
    itemModel: 'landingHolisticSolutionsItem',
    itemFields: ['id', 'name', 'description', 'image', 'color', 'imageUrl'],
  },
  {
    slug: 'knowledge-hub',
    model: 'landingKnowledgeHub',
    sectionFields: ['id', 'title', 'subtitle', 'actionLabel'],
    itemModel: 'landingKnowledgeHubItem',
    itemFields: [
      'id',
      'name',
      'description',
      'price',
      'color',
      'icon',
      'iconImage',
      'iconUrl',
      'priceAmount',
      'currency',
      'durationDays',
    ],
  },
  {
    slug: 'faithkart',
    model: 'landingFaithkart',
    sectionFields: ['id', 'title', 'subtitle', 'actionLabel'],
    itemModel: 'landingFaithkartItem',
    itemFields: [
      'id',
      'name',
      'color',
      'icon',
      'iconImage',
      'iconWidth',
      'iconHeight',
      'iconUrl',
    ],
  },
  {
    slug: 'wellness-insights',
    model: 'landingWellnessInsights',
    sectionFields: ['id', 'title', 'subtitle', 'actionLabel'],
    itemModel: 'landingWellnessInsightsItem',
    itemFields: [
      'id',
      'name',
      'description',
      'image',
      'color',
      'action',
      'imageUrl',
    ],
  },
  {
    slug: 'upcoming-rituals',
    model: 'landingUpcomingRituals',
    sectionFields: ['id', 'title'],
    itemModel: 'landingUpcomingRitualsItem',
    itemFields: [
      'id',
      'name',
      'badge',
      'benefitsTitle',
      'date',
      'color',
      'imageUrl',
      'imageAlt',
      'benefits',
    ],
  },
  {
    slug: 'meet-your-master',
    model: 'landingMeetYourMaster',
    sectionFields: [
      'id',
      'title',
      'name',
      'values',
      'imageUrl',
      'imageAlt',
      'actionLabel',
      'actionUrl',
    ],
  },
  {
    slug: 'corporate-wellness',
    model: 'landingCorporateWellness',
    sectionFields: [
      'id',
      'title',
      'headline',
      'description',
      'imageUrl',
      'imageAlt',
      'actionLabel',
    ],
  },
  {
    slug: 'success-stories',
    model: 'landingSuccessStories',
    sectionFields: ['id', 'title', 'subtitle'],
    itemModel: 'landingSuccessStoriesItem',
    itemFields: [
      'id',
      'name',
      'location',
      'photo',
      'color',
      'icon',
      'category',
      'quote',
      'imageUrl',
      'iconUrl',
    ],
  },
  {
    slug: 'video-testimonials',
    model: 'landingVideoTestimonials',
    sectionFields: ['id', 'title', 'subtitle'],
    itemModel: 'landingVideoTestimonialsItem',
    itemFields: ['id', 'name', 'role', 'color', 'imageUrl', 'videoUrl'],
  },
];
module.exports = { landingTables };
